### ISSUE TITLE
Add default travis.yml that sets up the db and migrates, etc.

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_cli#128]
Helpful travis.yml files:

* https://github.com/crystal-community/crystal-ann/blob/master/.travis.yml
* https://github.com/imdrasil/factory/blob/master/.travis.yml
* https://github.com/akwiatkowski/crystal_api/blob/master/.travis.yml

**Comment by paulcsmith** [comment]
Done :)

**Comment by jackturnbull** [comment]
Hi @paulcsmith sorry to revive an old issue but I think it's a valid enough place to ask; how do changes such as the travis config get decided upon? I'm just starting to try lucky and I like it a lot actually, although I do have certain concerns around future bloat and how this is planned to be handled within Lucky. Why not CircleCI, or both for example? Maybe even a SnapCI for good measure.

Slightly contrived, I know, but as I'm generating a new project I'm noticing myself removing large chunks of bolierplate much in the fashion I would with a Rails project and thus the questions of bloat come to mind!

Thanks for all your work though, nonetheless :)

**Comment by paulcsmith** [comment]
@jackturnbull That's a great question. There are a few thoughts that come to mind:

* Having some defaults in place makes it easier for the community to converge on a few technologies
* That, in turn, makes it easier to get help, onboard new people, and start new projects

The specific reason Travis was the one added is because it is much easier to set up, especially for Crystal, than Circle CI. It is also the default when creating a new Crystal project with `crystal init`. So Lucky just adds some Lucky specific stuff.

Another reason for it is that it is much easier to remove code you don't need than figure out how and where to add it later. It can annoy more opinionated/experienced users, but it is hugely beneficial to a lot of other people. Those are some of the main reasons for adding in some defaults for Lucky.

With that said, I think people should be able to some of the more commonly removed things. That's why in the next release there is a wizard #221 

If you have ideas for things you'd like to remove/add please feel free to make an issue along the lines of: "Consider making generated Travis setup optional" or something like that. I don't want to bloat the wizard too much so if you could also include how big of an annoyance it is that would also be great. For example, removing the travis.yml or removing turbolinks is fairly easy, but removing authentication or non-api components can be a lot more complex so it is in the wizard. 

I'm open to considering anything if there is a good reason for it though! I'm glad you brought this up!

**Comment by jackturnbull** [comment]
Thanks for the detailed reply, and the reasoning does make a lot of sense. Being totally fair removing a couple of self-standing config files is hardly a pain, but knowing software that's how it always starts. I wouldn't expect the wizard to be in charge of removing a Travis file as it's a simple enough task with it being uncoupled from any other functionality in-app.

It's been a while since I've ran a `crystal init`, so to that end I'd say that there is even less of an issue standardizing around Travis since this is encouraged at the language level. Having spent a the last couple of years in the Node.js world it's always surprising to see languages or frameworks standardize around _commercially hosted_ tools but that doesn't extend much further than just an opinion.

Maybe the initial question really becomes more rhetorical; how do you decide how coupled (or easy to remove) a change needs to be in order for it to be an allowable default? Given a modular enough structure it shouldn't be a big issue but thanks for explaining the reasoning!

**Comment by paulcsmith** [comment]
> how do you decide how coupled (or easy to remove) a change needs to be in order for it to be an allowable default?

Great question. I think there are multiple factors that I think of when deciding whether it should be generated

* What percentage of people will use? Is it a lot?
* How easy is it to remove if they don't want it?
* How much of a pain is it to keep in if a user doesn't want it?
* How hard is it to add if the user wants it?

So for auth my thinking would be:

* What percentage of people will use? Is it a lot? *Almost every app I've ever used needs it, but sometimes you just want a simple app to learn on, or you use Auth0 or something for auth*. I think a significant amount of people will find it useful though
* How easy is it to remove if they don't want it? *Not very easy to remove. Lots of generated folders and code*
* How much of a pain is it to keep in if a user doesn't want it? *A pretty big pain. Lots of unused code in models, etc.*
* How hard is it to add if the user wants it? *VERY hard. Takes a lot of time*

So, in this case, it is an *optional* addition because it's very useful when you need it, and hard to add otherwise, but it is also a pain to remove.

For something like Travis I'd say:

* What percentage of people will use? Is it a lot? *A decent amount will want CI. Travis has  a free tier. I'd say a decent size minority*
* How easy is it to remove if they don't want it? *Extremely*
* How much of a pain is it to keep in if a user doesn't want it? *Minor annoyance. Not in the main source code at all*
* How hard is it to add if the user wants it? *Quite hard. It took me many hours to figure out how to get chromedriver all set up*

So, in this case, it was not made optional because it's not hard to remove, it saves a lot of time if you need it.

I hope that clarifies even further and also helps show how I think through what to add. I feel like I should document this somewhere, but I'm not sure where. At least I can link to this in the future if needed

> .editorconfig was also in the same mental camp of 'not an issue but not expected.'

That is generated by crystal init 🤷‍♂️

**Comment by paulcsmith** [comment]
Always happy to answer questions and talk through the thought process. And if you disagree, LMK. I've changed my mind on a number of things so far :P

**Comment by paulcsmith** [comment]
And two more things I think of:

* How hard will it be to maintain? Auth is large and complex, but it is very valuable so it's worth it. Allowing for all kinds of different ORMs is even harder to maintain and makes it hard for people to choose what to use so likely will not be an option.
* How much do I think this is a *good* way of doing things? This is a bit more subjective, but sometimes this plays a part.

**Comment by jackturnbull** [comment]
> That is generated by crystal init 🤷‍♂️
Foiled by `crystal init` twice in one day 🤦‍♂️ 

Not at all trying to change your mind, but mainly see the rationale behind the decision making. The ORM opinion I agree on - I was almost going to stitch this project together as I would with Sinatra or Express but decided against it for this one. I don't think Rails lost a lot by mostly enforcing ActiveRecord for example.

Might have already skipped over it on my travels but this kind of ideology is what I'd quite like to see as part of the project documentation, be it in a contributing section or project overview section. Not specific figures such as "if 25% of people will use it, we'll do <x>" so much, but more of a "we're a light but opinioned feature-complete framework that makes reasonable trade-offs ..."/"We're aiming to be a modular plug-and-play framework with kitchen sinks included..." etc

Don't have much that I disagree with on the above in all honesty. Everything is a trade-off and I'm usually of the opinion that most open source projects that have some form of opinionated slant benefit from a BDFL, especially at an early stage and I can't argue with the logic behind the decision making. It might sound rude but I don't mean it to be, but having some form of statement on what kind of BDFL you are (from the viewpoint of lucky, rather than in the first person) would definitely help me with the decision making when choosing a framework.

**Comment by paulcsmith** [comment]
@jackturnbull I had to look up BDFL :P

Not rude at all. I appreciate the thought you've put behind your comments. I think having some kind of core philosophy would be useful, but I struggle to figure out what people are most interested in, and when.

* Should this go in a README? Right on the home page? A bit more buried in CONTRIBUTING.md?
* How in depth should it be?

Do you have any thoughts on that?
