### ISSUE TITLE
Create a .crystal-version file that matches the user's version of Crystal

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_cli#145]
When generating a new project, CLI now (#144) generates a `.crystal-version` file to go along with it. Right now it matches whatever version the CLI uses. This should change to match the version that's installed on the user's machine.

**Comment by paulcsmith** [comment]
I'm actually thinking it might be better to have a consistent version that ships with Lucky CLI rather than it depending on the user's system. I'm not sure this is a good idea, but it might be. For now, I'll close this but we can revisit later if it's an issue. I'm hoping we don't have to do anything though :)
