### ISSUE TITLE
cli doesn't pass --error-trace

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky_cli#581]
The CLI doesn't pass `--error-trace` and then tells the user to supply it.
```
$ lucky db.reset --error-trace
Showing last frame. Use --error-trace for full trace.
```

**Comment by jwoertink** [comment]
Ah, good catch. I did this for the `lucky watch` task manually https://github.com/luckyframework/lucky/blob/master/tasks/watch.cr#L206 but I think it would make sense to have the `--error-trace` flag get passed in to all tasks. https://github.com/luckyframework/lucky_cli/blob/master/src/build_and_run_task.cr#L31

One thing to think about though is that some tasks are pre-built. Like `lucky gen.page`. So if you passed the error trace flag, the binary would have already been compiled and the flag wouldn't make sense. We will have to take those in to consideration 🤔

**Comment by jwoertink** [comment]
Just because this came up again, and I'm thinking about it... I believe that the lucky command will first search to see if the task is precompiled, then just execute that binary. Maybe we can check to see if the flag is also being passed and if it is, it doesn't matter if there was a precompiled binary. Just recompile it again with the debug flags.

**Comment by BrucePerens** [comment]
Maybe you are overthinking this? If the task precompiled successfully, why
not ignore the flag?

**Comment by jwoertink** [comment]
🤔  hmm... good point... I guess the only reason you would pass that flag is during compilation errors, and the precompiled tasks wouldn't have any.
