### ISSUE TITLE
Crystal version for new apps is still 0.36.1

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#630]
https://github.com/luckyframework/lucky_cli/blob/a13e70f9422a27ef3b2d05201b01a74e67ace13b/src/web_app_skeleton/.crystal-version#L1

**Comment by jwoertink** [comment]
Yeah, I originally left that because I was thinking we would keep the lower end of what we support. When 1.1.0 comes out, we can drop support for 0.36, and set everything to 1.0. 

Thinking about it now, I guess new apps should be generated on the latest stuff, but internally we point to the min version? 🤔

**Comment by matthewmcgarvey** [comment]
If this was talking about 1.1 vs 1.2 I think I'd agree but I think it's best we try to go ahead and move everything to supporting minimum 1.0
