### ISSUE TITLE
normalize.scss dependency produces a warning

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_cli#640]
https://github.com/JohnAlbin/normalize-scss is no longer maintained and a a new project generated produces a warning on startup

```bash
8:34:02 PM assets.1       |  DEPRECATION WARNING
8:34:02 PM assets.1       |  : Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
8:34:02 PM assets.1       |  Recommendation: math.div($value, $relative-to)
8:34:02 PM assets.1       |  More info and automated migrator: https://sass-lang.com/d/slash-div
8:34:02 PM assets.1       |     ╷
8:34:02 PM assets.1       |  16 │     @return ($value / $relative-to) * 1em;
8:34:02 PM assets.1       |     │              ^^^^^^^^^^^^^^^^^^^^^
8:34:02 PM assets.1       |     ╵
8:34:02 PM assets.1       |      node_modules/normalize-scss/sass/normalize/_vertical-rhythm.scss 16:14  normalize-rhythm()
8:34:02 PM assets.1       |      node_modules/normalize-scss/sass/normalize/_vertical-rhythm.scss 27:14  normalize-font-size()
8:34:02 PM assets.1       |      node_modules/normalize-scss/sass/normalize/_normalize-mixin.scss 108:7  normalize()
8:34:02 PM assets.1       |      node_modules/normalize-scss/sass/normalize/_import-now.scss 11:1        @import
8:34:02 PM assets.1       |      src/css/app.scss 14:9                                                   root stylesheet
```

I'm pretty sure there's three solutions:
1. move to [normalize.css](https://necolas.github.io/normalize.css/) - I believe scss can import regular css files no problem and it's most likely to be the same maybe 🤷 
2. move to a different reset css package - I see [sanitize.css](https://github.com/csstools/sanitize.css) and [modern-normalize.css](https://github.com/sindresorhus/modern-normalize)
3. no longer include a css reset package

**Comment by stephendolan** [comment]
I'd personally advocate for option three. Most folks will bring their own CSS framework (I think?), and almost all of them will take care of this aspect anyways.

**Comment by matthewmcgarvey** [comment]
@stephendolan to be honest, it's up to you if no one else chimes in. I'm no CSS expert.

**Comment by jwoertink** [comment]
I like option 2.

The idea here is that out of the box, Lucky is "pretty". This was actually the selling point on why my company went with Lucky over Amber. I think @stephendolan is correct that most people will include their own CSS when working on a real project, but when you have someone that just wants to "taste" Lucky by running through a tutorial, or trying a few generators, it's better to have things looking nice and clean.

This modern-normalize looks pretty decent, and with it being smaller, it's a bit more out of the way.

**Comment by stephendolan** [comment]
I guess that what I'm struggling with is that I don't really see a difference in how pretty it is (this is on Chromium, so maybe the differences are more severe in Safari?):

Sign up with:
![CleanShot 2021-06-09 at 11 51 06](https://user-images.githubusercontent.com/6677875/121388257-56a5bd80-c919-11eb-87f3-184c8edd5686.png)

Sign up without:
![CleanShot 2021-06-09 at 11 52 02](https://user-images.githubusercontent.com/6677875/121388278-5a394480-c919-11eb-95b9-6588d4499d8b.png)

Profile with:
![CleanShot 2021-06-09 at 11 52 33](https://user-images.githubusercontent.com/6677875/121388296-5dcccb80-c919-11eb-8ac3-fd018c54bcee.png)

Profile without:
![CleanShot 2021-06-09 at 11 53 07](https://user-images.githubusercontent.com/6677875/121388303-602f2580-c919-11eb-8830-8073a5b7ac2a.png)

It seems decent enough without the extra CSS baggage that it wouldn't bog someone down who's trying out Lucky, but if we did want to keep it then I think we go with modern-normalize since it's what the Tailwind team uses, and they've probably done their research: https://github.com/tailwindlabs/tailwindcss/blob/master/package.json#L87

**Comment by jwoertink** [comment]
Strange. I thought without those styles it would smoosh up in the upper left corner... Doesn't the default render it in the center with some nice spacing? 🤔 

Thinking about it more, I guess browsers are a lot closer now than they were a few years back. Normalizing CSS is probably needed a lot less. If we do just get rid of this, do we still keep those default styles, or remove ALL of the CSS?

**Comment by stephendolan** [comment]
@jwoertink You might be thinking of the default CSS that we load in! I **do** think we should keep that:
https://github.com/luckyframework/lucky_cli/blob/master/src/browser_app_skeleton/src/css/app.scss#L19-L66

**Comment by jwoertink** [comment]
oh, yeah... wait what are we talking about here? 😂  I thought it was all the same thing lol

**Comment by jwoertink** [comment]
# :ditto:
> @stephendolan to be honest, it's up to you if no one else chimes in. I'm no CSS expert.
