### ISSUE TITLE
Feature Request: Select ORM for new app

### ISSUE THREAD

**Issue by grepsedawk** [luckyframework/lucky_cli#713]
With the direction of moving avram off of lucky's core, I think it would be a really nice feature addition to be able to select different ORMs when you generate a lucky app using the lucky CLI.

**Comment by grepsedawk** [comment]
This might require lucky adapters to get stuff like db:setup working, I'm not really sure.
But the concept behind this is just to "spin a lucky project using Jennifer", for example.

**Comment by jwoertink** [comment]
I totally get the appeal for this, but unfortunately, this is not something we will support. Everything within Lucky will always be under the assumption that you're using Avram as the ORM. The main reasons being that we have such a small core team, and that it gives us so much more control.

The reason we're removing Avram as a requirement is just because we also want to give people an escape hatch for when what Lucky provides isn't enough, or not quite what you need. Plus, there's already a few Lucky apps in the wild that don't require a DB at all, so having Avram is just unused code.

I think for something like this, I'd be ok with writing up some docs on how to integrate Jennifer (or Granite, etc...) in to a Lucky project. I would even be ok with having this on the website itself linked from [this alternate ORM section](https://luckyframework.org/guides/database/intro-to-avram-and-orms#alternate-orms)

**Comment by stephendolan** [comment]
FWIW, agreed with @jwoertink's thoughts on this.

**Comment by grepsedawk** [comment]
I agree 💯, I had started to think down this, it increases the surface area of lucky

If anything, I would think lucky generators on the IE Jennifer repo would make more sense, and match how IE rails does this type of thing
