### ISSUE TITLE
Update default host to 0.0.0.0

### ISSUE THREAD

**Issue by jkthorne** [luckyframework/lucky_cli#786]
I think in general the default host should be 0.0.0.0.  This is a special ip address that will allow binding to all ips. I believe this is default and this configuration was stopping lucky from working in docker.

**Comment by jwoertink** [comment]
In [this commit](https://github.com/luckyframework/lucky_cli/commit/2829ea45f1a6f94e21defb29b5e1ed150f99735e) it was originally `0.0.0.0`, but it was changed to `localhost` in [this commit](https://github.com/luckyframework/lucky_cli/commit/84ba24fcf49cc771e41d22887608ed4d051c6436) due to firewall issues on mac. Then changed to `127.0.0.1` in [this commit](https://github.com/luckyframework/lucky_cli/commit/11e3c605bf1ea50c28858a7b0d096aa36993a803) because of browsersync.

So now we've had this in 3 different ways and each time someone has reported an issue with the default... I'm not sure what the "Best" default should be here :man_shrugging: I've personally never had any issues with it being any of these values, but I'd like to get more input on this.

**Comment by wontruefree** [comment]
I am working on linux and deploying in docker.  deploying a development container is handy and this is breaking.

This does not mean we should change this but I just wanted to add some more context.

**Comment by matthewmcgarvey** [comment]
Just for reference, Rails uses `localhost` for development https://github.com/rails/rails/blob/c4194e560d4aaa5a6e6250ed82a1627aa6995d58/railties/lib/rails/commands/server/server_command.rb#L106-L108

See this PR on Rack for a reason why they default to `localhost` https://github.com/rack/rack/pull/514

The official docker docs for setting up Rails with docker compose show that they bind to `0.0.0.0` https://docs.docker.com/samples/rails/#define-the-project
